### PR TITLE
Update class diagram.

### PR DESCRIPTION
**Pull request by wurmmi**
Updated class diagram according to recent feedback.

### CODE REVIEW

**Comment by wurmmi** [comment]
it seems like Umlet and Umletino have a very different file format in the *.uxf file... :grimacing:

**Comment by skaupper** [comment]
it seems like Umletino outputs whole blocks in a single line

**Comment by wurmmi** [comment]
are you okay with it other than that?
please approve if you agree with it

**Comment by skaupper** [comment]
`Queue`: should be a vector of `QueueEntries`  

`QueueEntry` has a `votes` field but its `track` has this `votes` field as well  
an empty child class (like `Track`) is useless. maybe it's worth to rename it to `VotedTrack` and move the `votes` and `currentVote` field to it. a `PlaybackTrack` shouldn't need these fields anyway.

`generateSession` should take an optional nickname as string

maybe you can separate the network and datastore stuff a bit since it's pretty interweaved by now

**Comment by skaupper** [comment]
as you've already looked into the logging stuff: do you think we still need the `LoggingHandler`?

**Comment by skaupper** [comment]
`queryTracks` should return a `QueueStatus` result
`removeTrack` and `moveTrack` do not need to return a track anymore

**Comment by skaupper** [comment]
`queryTracks` should also have a second parameter `TCount`

**Comment by wurmmi** [comment]
alright - incorporated above feedback so far.

let's find a few minutes tomorrow to discuss the final diagram.

**Pull request merged**
