### PR TITLE
Update Endpoint documentation

### PR DESCRIPTION
**Pull request by skaupper**

### CODE REVIEW

**Comment by skaupper** [comment]
This change needs to be reflected in the class diagram. Does someone want to adapt it?

**Comment by skaupper** [comment]
@wurmmi can you incorporate the changes of this PR in the class diagram while updating it?
at this point we have a lot of different derivates of a track, so maybe a little restructuring is needed there (i dont mind if it is implemented using aggregation or inheritance)

**Comment by wurmmi** [comment]
okay, will try to get an overview of things that changed, and update the class diagram accordingly :+1:

**Comment by skaupper** [comment]
if you need some help deciphering it, I can assist in the evening

**Pull request merged**
