### PR TITLE
add rest client api

### PR DESCRIPTION
**Pull request by janeson332**

### CODE REVIEW

**Comment by skaupper** [comment]
The commit a397c32 needs to removed (sorry). Do you want to try it yourself or should I do that for you?

**Comment by janeson332** [comment]
better you do it

**Comment by skaupper** [comment]
since you have to update your local history too you need to
1. stash your current changes (`git add` them and use `git stash`)
2. reset your local  history to before the removed commit (`git reset --hard HEAD~4`)
3. pull the new history from the server (`git pull`)
4. apply your changes (`git stash pop`)

if you mess up step one your local changes are gone :)

**Comment by janeson332** [comment]
so, i have done the steps

**Comment by wurmmi** [comment]
this needs another rebase on latest master before it can be merged.. :upside_down_face: 
other than that.. LGTM

**Pull request merged**
