### PR TITLE
Make clang-format.

### PR DESCRIPTION
**Pull request by wurmmi**
`make clang-format` once again......

### CODE REVIEW

**Comment by skaupper** [comment]
maybe we should add a travis job which checks if everything is formatted well?^^

**Comment by wurmmi** [comment]
yeah, i thought about it, but then builds would probably constantly fail for developers, who are not using clang-format automated in their IDEs/editors... 
of course we could enforce `make clang-format` for every single commit that way..

**Comment by skaupper** [comment]
>  but then builds would probably constantly fail for developers, who are not using clang-format

isn't this exactly what we want?

**Comment by wurmmi** [comment]
alright, i will implement that in a separate PR (if there is time for playing around with things like that)

**Pull request merged**
